# -*- coding: utf-8 -*-
"""regular_falsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUriutQLnEArbjlxsMIlhUM3Bn-_kDA2
"""

import matplotlib.pyplot as plt
def fp_method(func,a,b,error_accept):
    def f(x):
      f=eval(func)
      return f

    #c_values=[]
    #error_values=[]


    i=0
    c_before=0
    c=(a*f(b)-b*f(a))/(f(b)-f(a))
    error=abs(c-c_before)
    #error_values.append(error)

    while error> error_accept:
      c_after=(a*f(b)-b*f(a))/(f(b)-f(a))

      if  f(a)* f(c_after)<0:
           error=abs(c_after-b)
          # error_values.append(error)
           b=c_after
           i=i+1

      else :
           error=abs(c_after-a)
           #error_values.append(error)
           a=c_after
           i=i+1

    print(error, "after", i, "iteration")

fp_method("4*x**3 + 3*x -3",0,1,0.05)